version: "3.9"

services:
  db:
    image: postgres:16
    container_name: okayo-exercice-db
    environment:
      POSTGRES_USER: okayo
      POSTGRES_PASSWORD: okayo
      POSTGRES_DB: okayo_db
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: okayo-exercice-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/okayo_db
      SPRING_DATASOURCE_USERNAME: okayo
      SPRING_DATASOURCE_PASSWORD: okayo
